<<<<<<< HEAD
twig:
    default_path: '%kernel.project_dir%/templates'
=======
# config/packages/twig.yaml

# …

twig:
    # …
    default_path: '%kernel.project_dir%/templates'
    globals:
        webmaster: "%env(WEBMASTER)%"
    form_themes:
        - 'bootstrap_4_layout.html.twig'
>>>>>>> f69f5ee33780f4aa43f67c7e47d416be5b5b7a35
