<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKrF6HIG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKrF6HIG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKrF6HIG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKrF6HIG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKrF6HIG\App_KernelDevDebugContainer([
    'container.build_hash' => 'KrF6HIG',
    'container.build_id' => 'c918f771',
    'container.build_time' => 1593180912,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKrF6HIG');
