<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAJHxLCQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAJHxLCQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAJHxLCQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAJHxLCQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAJHxLCQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'AJHxLCQ',
    'container.build_id' => '4f540e5a',
    'container.build_time' => 1593176333,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAJHxLCQ');
